repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        args:
          [--in-place, --remove-all-unused-imports, --remove-unused-variables]
        language: system
        types_or: [python, pyi]

      - id: isort
        name: isort
        entry: isort
        args: [--quiet]
        language: system
        types_or: [python, pyi]

      - id: black
        name: black
        entry: black
        args: [--quiet]
        language: system
        types_or: [python, pyi]
